server:
    port: 8772

spring:
    application:
        name: server2    
    cloud:
        discovery:
            service-id: ${spring.application.name}
            enablrd: true
    
eureka:
  instance:  
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka